### ISSUE TITLE
Add support for custom translation instructions

### ISSUE THREAD

**Issue by FidelusAleksander** [FidelusAleksander/ai-translate-action#3]
## Feature Request

Add support for custom translation instructions that users can pass to modify the default translation behavior.

### Description
Currently, the action uses a fixed system prompt for translations. Adding support for custom instructions would allow users to further customize the translation behavior by providing additional context or requirements.

### Proposed Implementation
1. Add a new optional input parameter to `action.yml`:
```yaml
custom-instructions:
  description: >
    Optional additional instructions to customize the translation behavior.
    For example: "Use formal language" or "Maintain technical terminology unchanged"
  required: false
```

2. Modify the `translateText` function in `src/ai.ts` to accept and incorporate custom instructions:
```typescript
// Add customInstructions parameter with optional type
export async function translateText(
  text: string,
  targetLanguage: string,
  model: string,
  token: string,
  customInstructions?: string
): Promise<string> {
  // ...
  const systemPrompt = `You are a highly skilled ${targetLanguage} translator.
    Your responsibilities:
    - Translate the provided text to ${targetLanguage}
    - Preserve the meaning, tone, formatting and style of the original text
    - Detect the source language automatically
    - Return only the translation, no explanations or notes
    ${customInstructions ? `\nAdditional instructions:\n${customInstructions}` : ''}

    You will receive the text to translate in the user message.`;
  // ...
}
```

3. Update tests to cover the new functionality

### Example Usage
```yaml
- uses: FidelusAleksander/ai-translate@v1
  with:
    text: "Hello, world!"
    target-language: "Japanese"
    custom-instructions: "Use formal language and maintain any technical terms in English"
```

### Benefits
- Allows users to customize translation behavior for specific needs
- Enables fine-tuning of language formality, technical term handling, etc.
- Maintains backward compatibility as the parameter is optional

### Tasks
- [ ] Add `custom-instructions` parameter to action.yml
- [ ] Update translateText function to handle custom instructions
- [ ] Add tests for custom instructions functionality
- [ ] Update documentation with examples and use cases
- [ ] Add input validation if needed
